# Generated by Django 6.0.4 on 2026-04-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_genre_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_active',
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('coming_soon', 'Próximamente'), ('archived', 'Archivado')], default='draft', max_length=20),
        ),
    ]
