# Generated by Django 6.0.4 on 2026-04-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_genre_slug_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
